name = "raffle-worker"
main = "worker/src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

[env.production]
vars = { NETWORK = "mainnet-beta", ODDS_MODE = "sqrt", MAX_WEIGHT_RATIO = "5", MIN_BALANCE_FOR_ELIGIBILITY = "0" }

[[kv_namespaces]]
binding = "KV_RAFFLE"
id = "adb78fd83f524dd283a2db8868795ac1"

[[d1_databases]]
binding = "D1_RAFFLE"
database_name = "raffle-db"
database_id = "a0b797f9-ee8b-4302-bbc2-7af64cb84e2a"

[triggers]
crons = ["*/20 * * * *"]

