name = "rewards-tracker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NETWORK = "mainnet-beta"

[[d1_databases]]
binding = "D1_CLAIMS"
database_name = "creator-claims"
database_id = "cc6fe3eb-3302-48f5-b995-6befe96d359d"

[[kv_namespaces]]
binding = "KV_SUMMARY"
id = "56de0bbb945b4f908cc3a56b1eb0bf8e"

[triggers]
crons = ["* * * * *"]

[[services]]
binding = "RAFFLE_SERVICE"
service = "raffle-worker"

