name = "rewards-tracker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NETWORK = "mainnet-beta"
CREATOR_WALLET = "8NwUT5jyjPdWcjjWrqTQNwuGiRZMrS6o3pwYTE3Kjwfi"
TZ = "Australia/Brisbane"

# Set these as secrets via wrangler secret put:
# WEBHOOK_SECRET = "<set-via-secret>"
# HELIUS_API_KEY = "<set-via-secret>"
# ALCHEMY_API_KEY = "<set-via-secret>"
# ALCHEMY_RPC_URL = "https://solana-mainnet.g.alchemy.com/v2/<KEY>"
# BACKFILL_TOKEN = "<set-via-secret>"

[[d1_databases]]
binding = "D1_CLAIMS"
database_name = "creator-claims"
database_id = "cc6fe3eb-3302-48f5-b995-6befe96d359d"

[[kv_namespaces]]
binding = "KV_SUMMARY"
id = "56de0bbb945b4f908cc3a56b1eb0bf8e"

[triggers]
crons = ["0,15,30,45 * * * *"]

[[services]]
binding = "RAFFLE_SERVICE"
service = "raffle-worker"

